### ISSUE TITLE
[Improvement]  HDFS_URI will be null if we run a single UT method.

### ISSUE THREAD

**Issue by xianjingfeng** [apache/incubator-uniffle#375] opened 2022-11-29 08:36 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

HDFS_URI will be null if we run a single UT method.
https://github.com/apache/incubator-uniffle/blob/c503f8f8ee522f67551652c5821cc1a7feb92ef7/integration-test/common/src/test/java/org/apache/uniffle/test/ShuffleServerWithMemLocalHdfsTest.java#L59

Several other UTs have the same problem.

### How should we improve?

Assign value in `setupServers`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jerqi** [comment] 2022-11-29 08:48
Could you give a way to reproduce the problem?

**Comment by xianjingfeng** [comment] 2022-11-29 10:35
![sc-20221129181224](https://user-images.githubusercontent.com/11752250/204506904-b5e40816-34d4-48a3-a9ad-43175408a79d.png)

**Comment by jerqi** [comment] 2022-11-29 11:53
I can't reproduce it
<img width="592" alt="企业微信截图_d2c7b81e-33b0-4067-ae64-ee6be96f5e39" src="https://user-images.githubusercontent.com/8159038/204522141-260d0ff8-bcdf-4544-9439-cc98387f8ff6.png">

**Comment by xianjingfeng** [comment] 2022-11-30 02:20
> I can't reproduce it 

Not run `ShuffleServerWithMemLocalHdfsTest`.
Try to run `ShuffleServerWithMemLocalHdfsTest.memoryLocalFileHDFSReadWithFilterTest`
It only appears when execute a single method

**Comment by jerqi** [comment] 2022-11-30 02:37
Could the maven reproduce this problem?

**Comment by xianjingfeng** [comment] 2022-11-30 02:45
> Could the maven reproduce this problem?

```shell
mvn -Dtest=org.apache.uniffle.test.ShuffleServerWithMemLocalHdfsTest#memoryLocalFileHDFSReadWithFilterTest test
```
This is ok.

**Comment by jerqi** [comment] 2022-11-30 02:46
> > Could the maven reproduce this problem?
> 
> ```shell
> mvn -Dtest=org.apache.uniffle.test.ShuffleServerWithMemLocalHdfsTest#memoryLocalFileHDFSReadWithFilterTest test
> ```
> 
> This is ok.

I guess this problem is related to IDEA.

**Comment by jerqi** [comment] 2022-11-30 02:47
So I think we should close this issue.

**Comment by xianjingfeng** [comment] 2022-11-30 02:53
I think we should consider if it is reasonable first. Whether `@BeforeAll` of parent class is always execure before the assignment of static variables.

**Comment by jerqi** [comment] 2022-11-30 03:06
I think that there is no problem about grammar.

**Closed** 2022-11-30 04:23 UTC
Labels: good first issue
