### ISSUE TITLE
[Bug] StagingBuffer reference remain when it has been deleted

### ISSUE THREAD

**Issue by zuston** [apache/incubator-uniffle#1308] opened 2023-11-10 08:17 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-uniffle/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I print out the arc reference count of the stagingBuffer in memoryStore before deleting from the dashmap in the method of `purge` , it's 2. This is strange, which means the data will remain.

### Affects Version(s)

master

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zuston** [comment] 2023-11-10 08:17
Are you interested on this ? @wenlongbrother

**Comment by wenlongbrother** [comment] 2023-11-10 10:28
Hi @zuston I am interested it. Can you assign it to me? I will complete in next week

**Comment by wenlongbrother** [comment] 2023-11-19 13:58
Hi @zuston , I reproduce the problem you mentioned according to the following steps:
## 1. I add some test code to reproduce this issue, like below
```rust
async fn purge(&self, app_id: String) -> Result<()> {
        // free allocated
        let released_size = self.discard_tickets(app_id.as_str(), None);
        self.budget.free_allocated(released_size).await?;
        info!(
            "free allocated buffer size:[{}] for app:[{}]",
            released_size,
            app_id.as_str()
        );

        // remove the corresponding app's data
        let read_only_state_view = self.state.clone().into_read_only();
        let mut _removed_list = vec![];
        for entry in read_only_state_view.iter() {
            let pid = entry.0;
            if pid.app_id == app_id {
                _removed_list.push(pid);
            }
        }

        let mut used = 0;
        for removed_pid in _removed_list {
            if let Some(entry) = self.state.get(removed_pid) {
                // get arc reference count
                let arc_ref_count = Arc::strong_count(&entry.value());

                println!("Arc reference count for StagingBuffer before removal: {}", arc_ref_count);
            }
            if let Some(entry) = self.state.remove(removed_pid) {
                used += entry.1.lock().await.total_size;
            }
        }

        // free used
        self.budget.free_used(used).await?;

        info!(
            "removed used buffer size:[{}] for app:[{}]",
            used,
            app_id.as_str()
        );

        Ok(())
    }
```
## 2. After this I run test_purge to observe resut.
Here is result:
<img width="492" alt="image" src="https://github.com/apache/incubator-uniffle/assets/50658515/1088627b-503f-4cb1-b2b7-401cdd53659f">

## 3.  I add some test code in **purge**

```rust

    async fn purge(&self, app_id: String) -> Result<()> {
        // free allocated
        let released_size = self.discard_tickets(app_id.as_str(), None);
        self.budget.free_allocated(released_size).await?;
        info!(
            "free allocated buffer size:[{}] for app:[{}]",
            released_size,
            app_id.as_str()
        );

        // print reference count before clone
        for entry in self.state.iter() {
            if entry.key().app_id == app_id {
                let arc_ref_count = Arc::strong_count(entry.value());
                println!("Arc reference count for value with app_id '{}': {}, before clone", app_id, arc_ref_count);
            }
        }

        // remove the corresponding app's data
        let read_only_state_view = self.state.clone().into_read_only();
       
        // print reference count after clone
        for entry in self.state.iter() {
            if entry.key().app_id == app_id {
                let arc_ref_count = Arc::strong_count(entry.value());
                println!("Arc reference count for value with app_id '{}': {}, after clone", app_id, arc_ref_count);
            }
        }

        let mut _removed_list = vec![];
        for entry in read_only_state_view.iter() {
            let pid = entry.0;
            if pid.app_id == app_id {
                _removed_list.push(pid);
            }
        }

        let mut used = 0;
        for removed_pid in _removed_list {
            if let Some(entry) = self.state.get(removed_pid) {
                // get arc reference count
                let arc_ref_count = Arc::strong_count(&entry.value());

                println!("Arc reference count for StagingBuffer before removal: {}", arc_ref_count);
            }
            if let Some(entry) = self.state.remove(removed_pid) {
                used += entry.1.lock().await.total_size;
            }
        }

        // free used
        self.budget.free_used(used).await?;

        info!(
            "removed used buffer size:[{}] for app:[{}]",
            used,
            app_id.as_str()
        );

        Ok(())
    }
```

I got this result
<img width="693" alt="image" src="https://github.com/apache/incubator-uniffle/assets/50658515/f626a640-533c-47d4-b9b0-99a2f2d5b7ce">

So I suspect the problem lies in the **clone()** method.

## 4. I try to search some information to explain the problem. 
Here is what I searched:
```doc
When you clone an Arc<T> (Atomic Reference Count) instance, several things happen, reflecting the design goals and use cases of Arc:

What Happens
Incrementing the Reference Count:
Inside Arc, there's an atomic reference count. When you clone an Arc, this count is safely incremented by one. This increment is an atomic operation, ensuring thread safety even in multi-threaded contexts. It means the count is adjusted without interference from other threads that might simultaneously access the Arc.

Creating a New Arc Instance:
The clone operation creates a new Arc instance. This new instance shares ownership of the underlying data with the original Arc instance. Both point to the same data in memory, but now there are two references to it.

Why It's Designed This Way
Shared Ownership:
Arc enables multiple owners (in the form of Arc instances) to share the same piece of data. Cloning an Arc doesn't duplicate the data it points to; instead, it just creates another pointer to the data, indicating that there's another owner.

Thread Safety:
The atomic increment of the reference count ensures that Arc can be used safely across threads without the need for additional synchronization mechanisms. This is crucial for concurrent programming in Rust.

Automatic Memory Management:
Arc automatically deallocates the data it points to when the last Arc pointing to that data goes out of scope. This automatic deallocation is a result of the reference count going to zero, indicating no more owners.

Preventing Premature Deallocation:
Incrementing the reference count on cloning prevents the data from being deallocated while it's still in use. If the count didn't increase on cloning, the data could be deallocated while other Arc instances are still using it, leading to undefined behavior.

Suitability for Concurrent Use:
Since Rust emphasizes safety, especially in concurrent scenarios, Arc provides a way to safely and efficiently manage data shared across threads without the explicit use of locks (though you might still need locks or other synchronization for mutating shared data).

In summary, Arc's design around cloning and reference counting is focused on enabling safe, concurrent sharing of immutable data, with automatic and efficient memory management.
```
## 5. Get weak reference to ensure purge can successfully free memory
To verify that the purge method correctly reduces the reference count of instances of Arc < Mutex < StagingBuffer > >, resulting in related resources being released. I use below code:

```rust
      // get weak reference to ensure purge can successfully free memory
        let weak_ref_before = store.state.get(&uid)
            .map(|entry| Arc::downgrade(&entry.value()));
        assert!(weak_ref_before.is_some(), "Failed to obtain weak reference before purge");

        // purge
        runtime.wait(store.purge(app_id.to_string())).expect("");
        assert!(weak_ref_before.clone().unwrap().upgrade().is_none(), "Arc should not exist after purge");
```

## 6. Conclusion
I guess when the purge method returns, stagebuffer should be recycled because his reference count is 0

**Comment by wenlongbrother** [comment] 2023-11-19 13:58
> Hi @zuston , I reproduce the problem you mentioned according to the following steps:
> 
> ## 1. I add some test code to reproduce this issue, like below
> ```rust
> async fn purge(&self, app_id: String) -> Result<()> {
>         // free allocated
>         let released_size = self.discard_tickets(app_id.as_str(), None);
>         self.budget.free_allocated(released_size).await?;
>         info!(
>             "free allocated buffer size:[{}] for app:[{}]",
>             released_size,
>             app_id.as_str()
>         );
> 
>         // remove the corresponding app's data
>         let read_only_state_view = self.state.clone().into_read_only();
>         let mut _removed_list = vec![];
>         for entry in read_only_state_view.iter() {
>             let pid = entry.0;
>             if pid.app_id == app_id {
>                 _removed_list.push(pid);
>             }
>         }
> 
>         let mut used = 0;
>         for removed_pid in _removed_list {
>             if let Some(entry) = self.state.get(removed_pid) {
>                 // get arc reference count
>                 let arc_ref_count = Arc::strong_count(&entry.value());
> 
>                 println!("Arc reference count for StagingBuffer before removal: {}", arc_ref_count);
>             }
>             if let Some(entry) = self.state.remove(removed_pid) {
>                 used += entry.1.lock().await.total_size;
>             }
>         }
> 
>         // free used
>         self.budget.free_used(used).await?;
> 
>         info!(
>             "removed used buffer size:[{}] for app:[{}]",
>             used,
>             app_id.as_str()
>         );
> 
>         Ok(())
>     }
> ```
> 
> ## 2. After this I run test_purge to observe resut.
> Here is result: <img alt="image" width="492" src="https://user-images.githubusercontent.com/50658515/284062088-1088627b-503f-4cb1-b2b7-401cdd53659f.png">
> 
> ## 3. I add some test code in **purge**
> ```rust
>     async fn purge(&self, app_id: String) -> Result<()> {
>         // free allocated
>         let released_size = self.discard_tickets(app_id.as_str(), None);
>         self.budget.free_allocated(released_size).await?;
>         info!(
>             "free allocated buffer size:[{}] for app:[{}]",
>             released_size,
>             app_id.as_str()
>         );
> 
>         // print reference count before clone
>         for entry in self.state.iter() {
>             if entry.key().app_id == app_id {
>                 let arc_ref_count = Arc::strong_count(entry.value());
>                 println!("Arc reference count for value with app_id '{}': {}, before clone", app_id, arc_ref_count);
>             }
>         }
> 
>         // remove the corresponding app's data
>         let read_only_state_view = self.state.clone().into_read_only();
>        
>         // print reference count after clone
>         for entry in self.state.iter() {
>             if entry.key().app_id == app_id {
>                 let arc_ref_count = Arc::strong_count(entry.value());
>                 println!("Arc reference count for value with app_id '{}': {}, after clone", app_id, arc_ref_count);
>             }
>         }
> 
>         let mut _removed_list = vec![];
>         for entry in read_only_state_view.iter() {
>             let pid = entry.0;
>             if pid.app_id == app_id {
>                 _removed_list.push(pid);
>             }
>         }
> 
>         let mut used = 0;
>         for removed_pid in _removed_list {
>             if let Some(entry) = self.state.get(removed_pid) {
>                 // get arc reference count
>                 let arc_ref_count = Arc::strong_count(&entry.value());
> 
>                 println!("Arc reference count for StagingBuffer before removal: {}", arc_ref_count);
>             }
>             if let Some(entry) = self.state.remove(removed_pid) {
>                 used += entry.1.lock().await.total_size;
>             }
>         }
> 
>         // free used
>         self.budget.free_used(used).await?;
> 
>         info!(
>             "removed used buffer size:[{}] for app:[{}]",
>             used,
>             app_id.as_str()
>         );
> 
>         Ok(())
>     }
> ```
> 
> I got this result <img alt="image" width="693" src="https://user-images.githubusercontent.com/50658515/284062925-f626a640-533c-47d4-b9b0-99a2f2d5b7ce.png">
> 
> So I suspect the problem lies in the **clone()** method.
> 
> ## 4. I try to search some information to explain the problem.
> Here is what I searched:
> 
> ```
> When you clone an Arc<T> (Atomic Reference Count) instance, several things happen, reflecting the design goals and use cases of Arc:
> 
> What Happens
> Incrementing the Reference Count:
> Inside Arc, there's an atomic reference count. When you clone an Arc, this count is safely incremented by one. This increment is an atomic operation, ensuring thread safety even in multi-threaded contexts. It means the count is adjusted without interference from other threads that might simultaneously access the Arc.
> 
> Creating a New Arc Instance:
> The clone operation creates a new Arc instance. This new instance shares ownership of the underlying data with the original Arc instance. Both point to the same data in memory, but now there are two references to it.
> 
> Why It's Designed This Way
> Shared Ownership:
> Arc enables multiple owners (in the form of Arc instances) to share the same piece of data. Cloning an Arc doesn't duplicate the data it points to; instead, it just creates another pointer to the data, indicating that there's another owner.
> 
> Thread Safety:
> The atomic increment of the reference count ensures that Arc can be used safely across threads without the need for additional synchronization mechanisms. This is crucial for concurrent programming in Rust.
> 
> Automatic Memory Management:
> Arc automatically deallocates the data it points to when the last Arc pointing to that data goes out of scope. This automatic deallocation is a result of the reference count going to zero, indicating no more owners.
> 
> Preventing Premature Deallocation:
> Incrementing the reference count on cloning prevents the data from being deallocated while it's still in use. If the count didn't increase on cloning, the data could be deallocated while other Arc instances are still using it, leading to undefined behavior.
> 
> Suitability for Concurrent Use:
> Since Rust emphasizes safety, especially in concurrent scenarios, Arc provides a way to safely and efficiently manage data shared across threads without the explicit use of locks (though you might still need locks or other synchronization for mutating shared data).
> 
> In summary, Arc's design around cloning and reference counting is focused on enabling safe, concurrent sharing of immutable data, with automatic and efficient memory management.
> ```
> 
> ## 5. Get weak reference to ensure purge can successfully free memory
> To verify that the purge method correctly reduces the reference count of instances of Arc < Mutex < StagingBuffer > >, resulting in related resources being released. I use below code:
> 
> ```rust
>       // get weak reference to ensure purge can successfully free memory
>         let weak_ref_before = store.state.get(&uid)
>             .map(|entry| Arc::downgrade(&entry.value()));
>         assert!(weak_ref_before.is_some(), "Failed to obtain weak reference before purge");
> 
>         // purge
>         runtime.wait(store.purge(app_id.to_string())).expect("");
>         assert!(weak_ref_before.clone().unwrap().upgrade().is_none(), "Arc should not exist after purge");
> ```
> 
> ## 6. Conclusion
> I guess when the purge method returns, stagebuffer should be recycled because his reference count is 0

Please correct me if I am wrong, thank you.

**Comment by zuston** [comment] 2023-11-20 03:31
Got your point. Really thanks @wenlongbrother

**Closed** 2023-11-22 07:23 UTC
